Initial `<daedalus_output>` class
jameel-institute/daedalus pull request #22
Opened 2024-09-11 14:01 UTC by pratikunterwegs

This PR adds a simple `<daedalus_output>` class, which is a list holding:
- `model_data` - a data.frame of the compartmental model results;
- `country_parameters` - a list of country parameters; basically an unclassed `<daedalus_country>` object;
- `infection_parameters` - an unclassed `<daedalus_infection>` object;
- `response_data` - a list with information on the response strategy and implementation level. In a follow-up PR this will also hold a sub-list of closure start and end times.

The `get_data()` method applied to `<daedalus_output>` returns the model data by default when no element is specified.

My current thinking is that a `calculate_costs()` function would operate on this output and return a total/disaggregated cost that can be returned by the R API.

2024-09-12 11:09 UTC, richfitz requested changes

2024-09-12 11:09 UTC, richfitz commented on R/class_daedalus.R
> +  }
This will lead to sapply-like pathologies, I'd suggest considering another approach.  If the vector `to_get` is ever computed then the return type here is unknowable.

I'd suggest either adding a `single_value` argument to this, or just always returning a list

2024-09-12 13:29 UTC, pratikunterwegs commented on R/class_daedalus.R
> +  }
Sure, I'll restrict it to a single element - but I think it's worth keeping the `get_data(x, y = NULL)` returning the timeseries data rather than the user having to specify that, the friction on that could get annoying for users.

2024-09-12 13:33 UTC, pratikunterwegs commented on R/class_daedalus.R
> +  }
And since this issue also exists with the infection and country classes, I'll fix the same thing for those in this PR as well.

2024-09-12 14:51 UTC, pratikunterwegs commented
Checks on this will fail due to a documentation warning but should be fixed once this PR is rebased on #20 or rather main.

2024-09-13 09:46 UTC, pratikunterwegs commented
Checks now passing after rebasing; `sapply()`-like behaviour has been removed.

2024-09-13 11:38 UTC, richfitz approved these changes

2024-09-13 11:51 UTC, merged