Add cost function
jameel-institute/daedalus pull request #25
Opened 2024-09-17 14:37 UTC by pratikunterwegs

This PR adds the function `get_costs()` to calculate pandemic costs from a `<daedalus_output>` object.

The best place to see the use case is in the newly added vignette, "pandemic_costs.Rmd".

Costs are calculated as:

## Economic costs

1. Closures: Daily GVA per sector $\times$ (1 - openess) $\times$ closure duration in days;
2. Absences: Daily GVA per sector, accounting for closures $\times$ proportion workers available, for each day; workers are available if not infectious, hospitalised, or dead.

## Education costs

Education costs are calculated as the GVA loss from closures and absences in the education sector. They are not included in the economic costs when presented to the user.

## Life years lost

Life expectancy for each age group $\times$ value of a statistical life. There doesn't seem to be any discounting for age.

## Other changes:

1. Added raw data on life expectancy and value of a life year (VLY) in multiple countries;
2. Converted (1) into package data `life_value` for age-group-wise data on the value of a statistical life in each country (VSL).
    - Number of countries reduced to 67 with Hong Kong and Taiwan removed due to lack of life expectancy or value data.
3. `<daedalus_country>` class automatically pulls in VSL data when created;
4. `<daedalus_output>` now includes total simulation time and openness coefficient data (used in cost calculation);

2024-09-17 14:50 UTC, pratikunterwegs commented
Weird case of the test workflow failing when the R CMD check workflow passes; the check workflow includes running the tests. Will look into it.

2024-09-17 15:09 UTC, pratikunterwegs commented
Unsure what the issue is here as I can't reproduce this error locally. My next guess is that there's an issue with the workflow in either {spelling} or {testthat}.

2024-09-18 14:18 UTC, pratikunterwegs commented
Removed {data.table} which fixes the failing coverage workflow.

2024-09-19 12:12 UTC, richfitz approved these changes
A couple of small suggestions to clarify the calculation, but I don't at all feel strongly on this

2024-09-19 15:07 UTC, pratikunterwegs commented on R/costs.R
> +  )$value
Will switch to `tapply()` here, lower-level is better.

2024-09-19 15:08 UTC, pratikunterwegs commented on R/costs.R
> +  )
I haven't full got whether this suggested snippet is accounting for the reduction in potential GVA due to closures, but will look at making it easier to read.

2024-09-20 09:35 UTC, pratikunterwegs commented on R/costs.R
> +  )
I've updated this bit in https://github.com/jameel-institute/daedalus/pull/25/commits/4b3fa792180648ca9b81007af2eba162cc81a8b2 to use matrix multiplication, with a sub-matrix scaled by openness - hopefully that's easier to read.

2024-09-20 10:04 UTC, richfitz requested changes

2024-09-20 10:04 UTC, richfitz commented on R/class_country.R
> +        lower = 0, upper = 1e7 # reasonable upper limit
Below on l406:

```
prepare_parameters.daedalus_country <- function(x) {
```

becomes

```
prepare_parameters.daedalus_country <- function(x, ...) {
```

to fix that build. New check in r-devel perhaps?

2024-09-20 10:10 UTC, pratikunterwegs commented on R/class_country.R
> +        lower = 0, upper = 1e7 # reasonable upper limit
Yep just spotted this when the build failed!

2024-09-20 13:14 UTC, merged