Initial implementation of spontaneous social distancing
jameel-institute/daedalus pull request #28
Opened 2024-09-23 08:55 UTC by pratikunterwegs

This PR adds a first version of a function to modify the infection transmission rate based on the number of new deaths. The intention is to model public concern that leads to a spontaneous reduction in social contacts independent of any response measures.

The coefficient function is hardcoded as an exponential decay between 1.0 (no concern) and a lower limit (maximum concern, and greatest possible reduction in social contacts; defaults to 0.2). The hardcoded decay rate is 0.01, or a 1.0% reduction for each additional death. This could be passed flexibly as a model or country parameter, but is not expected to be a major axis of variation for scenario analysis at this time.

2024-09-23 16:01 UTC, richfitz requested changes

2024-09-23 16:01 UTC, richfitz commented on R/ode.R
> +  new_deaths <- sum(d_state[, i_D, ])
So this is really the "expected number of deaths over one day, given the current *rate* of deaths" rather than the (probably very similar value) "number of deaths observed over the last day"?

2024-09-23 16:01 UTC, richfitz commented on R/ode.R
> +  r0 <- r0 * ifelse(switch, get_distancing_coefficient(new_deaths), 1.0)
```suggestion
  r0 <- r0 * if (switch) get_distancing_coefficient(new_deaths) else 1.0
```

`ifelse` is vectorised, and also full of footguns

2024-09-24 08:43 UTC, pratikunterwegs commented on R/ode.R
> +  new_deaths <- sum(d_state[, i_D, ])
Yes - it's obviously unrealistic as lags in reporting are not accounted for. That's covered in the issue on YouTrack and needs revisiting at some future date.

Currently, I'm hoping there aren't huge spikes in deaths (which one might actually see due to reporting effects in real data!) that cause wild swings in the distancing coefficient.

2024-09-24 09:02 UTC, richfitz commented on R/ode.R
> +  new_deaths <- sum(d_state[, i_D, ])
I think your approach is totally reasonable, and not worth the complexity that dealing with lags involves

2024-09-24 09:02 UTC, richfitz approved these changes

2024-09-24 12:06 UTC, merged