Initial implementation of single-stratum vaccination
jameel-institute/daedalus pull request #29
Opened 2024-09-24 12:18 UTC by pratikunterwegs

This PR is WIP on adding vaccination to the model. This

- Total of two vaccine groups/strata - unvaccinated and vaccinated;

To do:
- [ ] Vaccination reduces susceptibility to infection;
- [ ] Vaccination rate maintained constant over time as a fraction of population, as susceptibles and recovered are reduced due to vaccination;
- [ ] Vaccination begins when response is triggered;
- [ ] Vaccination-to-response mapping is worked out, i.e., is vaccination activated in the 'no response' scenario?;
- [ ] Vaccination only for oldest age group;
- [ ] Vaccination up to the uptake limit terminates active response;
- [ ] Vaccination rate is taken from a strategy passed to `daedalus()`;
- [ ] Vaccine stockpiles are country/income-group specific and limit the number of vaccinations.

2024-09-26 08:49 UTC, richfitz requested changes

2024-09-26 08:49 UTC, richfitz commented on R/prepare_output.R
> +  data$Var5 <- rep(
Why assigning here to `Var5` to replace with `vaccine_group` later? Why not `data$vaccine_group <- ...` (and elsewhere here)

2024-09-26 09:00 UTC, pratikunterwegs commented on R/prepare_output.R
> +  data$Var5 <- rep(
No good reason really - that way I'd create new columns and subset out the ones we don't need. This saves a subset and adds a renaming operation. No preference either way.

2024-09-26 14:54 UTC, pratikunterwegs commented
Spotted a little issue with the closure activation and termination functions where the `state` hasn't been updated to reflect the newly added fourth dimension - will fix and push.

2024-09-27 10:00 UTC, pratikunterwegs commented
Fixed:
- a conditional in `scale_nu()` - $\nu$ is 0.0 if not finite;
- updated dims in state used in rootfinding-event functions;
- a failing test where vaccination led to increased deaths.

2024-09-27 10:51 UTC, richfitz approved these changes

2024-09-27 10:51 UTC, richfitz commented on R/vaccination.R
sorry about that!

2024-09-27 11:11 UTC, merged