Use Jameel Institute pkgdown template
jameel-institute/daedalus pull request #40
Opened 2024-10-18 10:29 UTC by pratikunterwegs

This PR updates the package to use the [Jameel Institute {pkgdown} template.](https://github.com/jameel-institute/jameelinst.rpkg.theme)

2024-10-21 07:44 UTC, richfitz requested changes

2024-10-21 07:44 UTC, richfitz commented on DESCRIPTION
> +    person("Richard", "Fitzjohn", role = "aut",
```suggestion
    person("Rich", "FitzJohn", role = "aut",
```

2024-10-21 07:44 UTC, richfitz commented on DESCRIPTION
> +    person("Richard", "Fitzjohn", role = "aut",
Can you put David in here too please?

2024-10-22 08:41 UTC, pratikunterwegs commented on DESCRIPTION
> +    person("Richard", "Fitzjohn", role = "aut",
Done!

2024-10-22 08:41 UTC, merged